### PR TITLE
Fix: missing empty lines between html end tags and start of code blocks

### PR DESCRIPTION
**Pull request by rwols**
See: https://spec.commonmark.org/0.29/#example-131

### CODE REVIEW

**Comment by rwols** [comment]
I'm starting to think it's intentional to not have an empty line 6f0790fad6b7

**Comment by rwols** [comment]
... but example 155 (https://spec.commonmark.org/0.29/#example-155) states that this input

````
<div>
bar
</div>
*foo*
````

is processed to

````
<div>
bar
</div>
*foo*
````

which seems to suggest that, for portability, an empty line is actually required

**Comment by KamasamaK** [comment]
I don't think it's intentional. Their newer PR #1287 explains that those newlines should be there.

**Comment by NTaylorMullen** [comment]
So technically newlines aren't required functionally from my experiments; however, I found that without them you lose VSCode colorization of the TypeScript blocks. Therefore, to ensure a nice editing experience we should have newlines after all of them 😄

**Review by NTaylorMullen — APPROVED** [review]

**Comment by rwols** [comment]
Did my commit vanish into thin air? :D I don't see it on the gh-pages branch.

**Comment by NTaylorMullen** [comment]
To be honest I thought I had addressed your fixes a lot earlier and then after seeing your PR figured I must have missed a few. It's possible your gh-pages wasn't sync'd when you initially made the changes :)

**Comment by rwols** [comment]
Alright, sounds good to me

**Pull request merged**
