### PR TITLE
Update 3.16 spec to include moniker request method

### PR DESCRIPTION
**Pull request by BertanAygun**

### CODE REVIEW

**Comment by dbaeumer** [comment]
Thanks again!

**Comment by kjeremy** [comment]
Can this be backed out and reapplied without the line ending changes?

**Comment by dbaeumer** [comment]
@kjeremy is this causing problems. I would actually prefer LF over CRLF since we use LF in the implementation project as well.

**Comment by kjeremy** [comment]
No it's all good.

**Comment by dbaeumer** [comment]
Thanks!

**Pull request merged**
