### PR TITLE
Add multirange support to range formatting

### PR DESCRIPTION
**Pull request by c-claeys**
Add multiRange support to the rangeFormatting method with a new list field in the request.

See also https://github.com/microsoft/language-server-protocol/issues/1536

### CODE REVIEW

**Comment by c-claeys** [comment]
@dbaeumer Let me know if you have any questions or concerns about this. I have commits partially completed to add support for this in both https://github.com/microsoft/vscode and https://github.com/microsoft/vscode-languageserver-node but they depend on choices made here.

**Comment by dbaeumer** [comment]
@c-claeys thanks for the PR. In general we don't add things to the specification without have an (prototype) implementation at least for one editor. 

I suggest that you continue with `ranges` and have an implementation in VS Code and the LSP nodes modules. If these implementations seem solid then we can start specing the behaviour.

**Review by c4nzin — APPROVED** [review]

**Comment by dbaeumer** [comment]
I will close the PR for now. We can reopen it when there is an implementation for at least one editor.

**Comment by tom-anders** [comment]
> I will close the PR for now. We can reopen it when there is an implementation for at least one editor.

Since it has been implemented in https://github.com/microsoft/vscode/pull/163190 now, can we reopen this issue?

**Comment by dbaeumer** [comment]
I can't since the fork for the PR got deleted.

**Comment by tom-anders** [comment]
@c-claeys Are you interested in updating this PR or opening a new one?

**Comment by c-claeys** [comment]
I'll open a new one. I think the old approach differed qualitatively from where we landed for the VSCode API. I deleted the fork too (looks like it's a support pain to restore).

**Pull request closed without merging**
