### PR TITLE
Add Annotation in the CompletionItemKind enum

### PR DESCRIPTION
**Pull request by kaloyan-raev**
Annotations are popular kind of completion items in Java, Scala and other programming languages.

### CODE REVIEW

**Comment by dbaeumer** [comment]
I like adding this but this needs adoption on clients sides as well.

**Comment by ljw1004** [comment]
Shouldn't it also be added in the SymbolKind enumeration? e.g. if you do a project-wide symbol search and the result is an annotation.

(I think it'd be good for users if they have consistent icons between autocomplete and project-wide-symbol-search).

**Comment by dbaeumer** [comment]
Closing in favour of https://github.com/Microsoft/language-server-protocol/issues/344 which contains Annotation.

**Comment by KimBurgess** [comment]
It looks like this may have been closed off in favour of a (still open, long running) discussion, rather than alternate PR. Is there a current recommended / well used alternative `SymbolKind` that can be used for annotations?

**Pull request closed without merging**
