### PR TITLE
Issue #782 - InitializationParams.clientName

### PR DESCRIPTION
**Pull request by mickaelistria**
This is already used by Eclipse LSP4J and related language servers and clients.

### CODE REVIEW

**Comment by dbaeumer** [comment]
Will merge into the new 3.15 release when I branch off.

**Comment by puremourning** [comment]
This new item it mandatory?! That’s a breaking change, right?

**Comment by mickaelistria** [comment]
@puremourning you're right, I'll make it optional.

**Comment by mickaelistria** [comment]
> @puremourning you're right, I'll make it optional.

Done, thanks for the review!

**Comment by puremourning** [comment]
You’re wecome! Thanks for sorting it :)

**Comment by dbaeumer** [comment]
Add to 3.15 branch with the following modification:

- name & version
- for client and server

The branch is https://github.com/microsoft/language-server-protocol/tree/dbaeumer/3.15

**Pull request closed without merging**
