### PR TITLE
Add DiagnosticTag to documentation

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**

### CODE REVIEW

**Comment by dbaeumer** [comment]
@Krzysztof-Cieslak thanks. I wanted to wait with this to batch a couple of more small improvements.

**Comment by KamasamaK** [comment]
Consider adding `Deprecated` tag as well. It is currently a [proposed tag for VS Code](https://github.com/microsoft/vscode/blob/03d1686da9224aadfe5c670ba86be5cd5649be9d/src/vs/vscode.proposed.d.ts#L1310).

**Comment by KamasamaK** [comment]
Also consider adding tag support as a capability.

**Comment by dbaeumer** [comment]
Updated spec on dbaeumer/3.15 branch. Added additional client capability.

**Pull request closed without merging**
