### PR TITLE
Change character offsets from UTF-16 codeunits to Unicode codepoints

### PR DESCRIPTION
**Pull request by soc**
Addresses https://github.com/Microsoft/language-server-protocol/issues/376.

### CODE REVIEW

**Comment by mikesamuel** [comment]
Should the commit message not note that this would break compatibility?
IIUC, *Position*s from clients written to version 3.16 would not work with servers complying with this change and vice versa.
The change in spec text should probably be accompanied by a non-normative note explaining how to manage that transition.  Without that, this would engender a lot of confusion.

**Comment by dbaeumer** [comment]
@soc we can't simply change the spec that way since it is a breaking change and makes most existing server non spec conformant. The right approach is to add a capability on the client and server side and to spec a corresponding handshake.

**Comment by soc** [comment]
@dbaeumer Did you check the date of this issue?

**Comment by dbaeumer** [comment]
@soc Sorry, I reacted based on @mikesamuel comment. Any objection to close the PR since as noted this needs more work

**Comment by mikesamuel** [comment]
Sorry for the confusion

**Comment by axelson** [comment]
@dbaeumer I think closing this particular PR only makes sense if @soc doesn't plan to update the PR based on your comment (as well as fix the merge conflict). But would you consider a similar PR that does add a capability on the client and server side and specs a corresponding handshake?

**Comment by soc** [comment]
Various implementations introduced some kind of encoding negotiation or changed the defaults already.

The world has moved on and the PR is obsolete.

**Comment by dbaeumer** [comment]
Yes, I would accept a PR that defines such a handshake and adds an implementation to one of the client and server libraries that are out there.

**Pull request closed without merging**
