### PR TITLE
align image paths in lsif/overview.md

### PR DESCRIPTION
**Pull request by patmejia**
### align image paths in `lsif/overview.md`
- update non-functional image links within `lsif/overview.md`.
- align paths for `hover.png`, `hoverResult.png`, `foldingRange.png`.

Compliance:
This pull request adheres to Microsoft's Open Source Code of Conduct.

### CODE REVIEW

**Comment by dbaeumer** [comment]
@patmejia this change will break the rendering of the images. 

image

Can you explain what your thinking behind this is.

**Comment by patmejia** [comment]
@dbaeumer, thanks for the review. 

understood that my pr could break image rendering. i see the project likely uses a static site generator (i.e. `Liquid templating syntax ({{ "/overviews/lsp/overview" | prepend: site.baseurl }})`, affecting how paths are resolved. 

likewise, [#1833 ](https://github.com/microsoft/language-server-protocol/pull/1833)

should i revert these changes or is there another fix you recommend?

**Comment by dbaeumer** [comment]
Since all images are rendered correctly I am actually not understanding what you want to fix / achieve. Could you please explain this.

**Comment by patmejia** [comment]
agree with observation.

**Pull request closed without merging**
