### PR TITLE
Update jdt.ls entry to reflect move to eclipse.org

### PR DESCRIPTION
**Pull request by gorkem**

### CODE REVIEW

**Comment by rcjsuen** [comment]
Congratulations to you and Fred and the rest of the team! :)

**Comment by egamma** [comment]
Congrats 🌷

**Comment by Kinou90100** [comment]
#1456 
#1455 
#1454 
#1453 
#1444 
#362
@Kinou90100
@Christoc90

**Review by Kinou90100 — COMMENTED** [review]
#1456 
#1455 
#1454 
#1453 
#1444 
#362
@Kinou90100
@Christoc90

**Pull request merged**
