### PR TITLE
ResponseMessage.result can be an array type

### PR DESCRIPTION
**Pull request by yxrkt**
Certain responses state that they can return arrays (Document Color Request, for example).

### CODE REVIEW

**Comment by dbaeumer** [comment]
Correct. Merged by hand into 3.17.

**Comment by darichey** [comment]
@dbaeumer Was this merged correctly? The current spec doesn't reflect the change.

**Comment by KamasamaK** [comment]
The commit history does not show that this was ever corrected for 3.17.

**Comment by dbaeumer** [comment]
Actually my conclusion was that `object` in TS includes `array` and therefore didn't add it. But this might not be obvious for everybody. But adding it might include confusion as well. May be we should add a comment somewhere.

**Comment by darichey** [comment]
That's fair, but `array | object` appears in other places in the spec (`RequestMessage.params`, `ResponseError.data`, `NotificationMessage.params`). 

Personally, I think that they should be consistent and that explicitly including `array` is more clear.

**Comment by dbaeumer** [comment]
Good point.

**Comment by dbaeumer** [comment]
Added `array`

**Pull request closed without merging**
