### PR TITLE
Add SignatureInformation#activeParameter support

### LINKED ISSUE #974: SignatureInformation.activeParameter
Just making sure there's an issue for @dbaeumer per https://github.com/microsoft/vscode/issues/94637#issuecomment-617697935.

### PR DESCRIPTION
**Pull request by KamasamaK**
Fixes #974

### CODE REVIEW

**Comment by rcjsuen** [comment]
@KamasamaK This diff (971b2cf911440e350d3146489439343b53fa910c) is massive. Did the newline characters get changed or something?

**Comment by KamasamaK** [comment]
It's unclear to me why it's doing that in the GitHub source diff. I've never had an issue with newline changes before and I'm not sure how to verify if that were the issue. I thought that Git normalized those, anyway. I've verified that I have "core.autocrlf" set to "true". The commit diff within VS Code only shows my 3 changes and I do not have it configured to ignore whitespace changes. If you are able to swap the GitHub diff from "source diff" to "rich diff" it becomes more clear what the 3 changes are.

**Comment by dbaeumer** [comment]
@KamasamaK thanks for the PR. Did the changes by hand to due the massive diff.

**Comment by KamasamaK** [comment]
Ok. I noticed some wording changes and commented on 5565f27a495129a5fde45d0bdad874dc6f2b404c about an incorrect description. It's also missing the addition to the changelog.

What is the meaning of "proposed state"? It's already shipped in the latest stable vscode.d.ts and the change seems trivial enough that I don't see it possibly changing for LSP.

**Comment by dbaeumer** [comment]
It is proposed in LSP. This is to signal that we still might change it. I always try to do it this way.

**Pull request closed without merging**
