### PR TITLE
Sorting language servers by Language

### PR DESCRIPTION
**Pull request by adelarsq**
Sorting language servers by Language 😄

### CODE REVIEW

**Comment by dbaeumer** [comment]
@adelarsq thanks and I thought the same that we should change the sort order a while ago.

Can you please sign the CLA. Otherwise we can't merge.

**Comment by adelarsq** [comment]
@dbaeumer I was on vacation. Signed now.

**Comment by mattacosta** [comment]
FYI: There's still a line at the top that says `The language servers are listed in chronological order of appearance`.

**Comment by adelarsq** [comment]
@mattacosta Thanks. I did update.

**Comment by adelarsq** [comment]
@mattacosta Thanks. I updated.

**Comment by apupier** [comment]
@adelarsq just to warn you that there is a conflict to resolve

**Comment by dbaeumer** [comment]
I resolved the merge conflicts.

**Pull request merged**
