### PR TITLE
Corrected names and registrationOptions for notebookDocument/sync notifications

### PR DESCRIPTION
**Pull request by 0xJonas**
`NotebookDocumentSyncOptions` and `NotebookDocumentSyncRegistrationOptions` were referred to incorrectly in a few places. The meta model was also missing `registrationOptions` for the _notebookDocument/sync_ notifications.

### CODE REVIEW

**Comment by 0xJonas** [comment]
@microsoft-github-policy-service agree

**Comment by dbaeumer** [comment]
@0xJonas thanks for the PR. Could you please remove the changes to the metaModel.json. That file is auto generated and maintained here: https://github.com/Microsoft/vscode-languageserver-node. Thanks

**Comment by dbaeumer** [comment]
For the meta model see: https://github.com/microsoft/vscode-languageserver-node/pull/1369

**Comment by 0xJonas** [comment]
The changes in the `metaModel.json` files have been reverted.

**Review by dbaeumer — APPROVED** [review]

**Review by alexdima — APPROVED** [review]

**Pull request merged**
