### PR TITLE
Support  `llmGenerated` property on `CodeAction`

### PR DESCRIPTION
**Pull request by StellaHuang95**
Addresses https://github.com/microsoft/vscode-languageserver-node/issues/1555

- Added `llmGeneratedSupport` to `CodeActionClientCapabilities`.
- Added `llmGenerated` to `CodeAction`.
- Marked both of them as `proposed`.

### CODE REVIEW

**Review by mfussenegger — COMMENTED** [review]
Wouldn't it be more flexible if this were just a `source` hint, which can be an arbitrary string, or an enum+string for some well defined code action sources where `llm` is one of them?
E.g. if LLM gets replaced by some newer tech, there wouldn't be need to introduce a `xyGenerated` property.

Then this also wouldn't need a client capability (because if the client shows a fancy icon or something shouldn't matter for servers)

**Comment by StellaHuang95** [comment]
Thanks for the feedback, I've updated to use `CodeActionTag` as suggested by Dirk. Please let me know if there's anything else you'd like me to address

**Comment by dbaeumer** [comment]
@StellaHuang95 we should use the same wording tweaks as proposed in https://github.com/microsoft/vscode-languageserver-node/pull/1557

**Review by dbaeumer — CHANGES_REQUESTED** [review]
We also need to add a client capability indicating that the client supports tags. If should go somewhere here  https://github.com/microsoft/language-server-protocol/blob/gh-pages/_specifications/lsp/3.18/language/codeAction.md#L110 and should be named `tagSupport`. You can use this https://github.com/microsoft/language-server-protocol/blob/gh-pages/_specifications/lsp/3.18/language/completion.md#L74 as a blueprint. 

Sorry, forgot about that.

**Review by dbaeumer — APPROVED** [review]

**Review by connor4312 — APPROVED** [review]

**Pull request merged**
